version: '3.8'

services:
  web:
    container_name: utilapps
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3015:3000"
    restart: always
    environment:
      - NODE_ENV=production
